name: Downloa

on: push

jobs:
  download-youtube-video:
    runs-on: ubuntu-latest

    steps:
      - name: 部署 rclone
        run: wget -c 'https://downloads.rclone.org/v1.59.2/rclone-v1.59.2-linux-amd64.zip' && unzip 'rclone-v1.59.2-linux-amd64.zip' && echo '${{ secrets.RCLONE_CONF }}' > rclone.conf


      - name: 部署 ffmpeg
        #run: wget -c 'https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz' && tar -xf 'ffmpeg-git-amd64-static.tar.xz'
        run: rclone-v1.59.2-linux-amd64/rclone copy --config rclone.conf -P 'OneDrive_ty_30GB:ffmpeg-git-amd64-static.tar.xz' ./ && tar -xf ffmpeg-git-amd64-static.tar.xz

      - name: 部署 yt-dlp
        run: wget -c 'https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp' && ls -Alh ./yt-dlp && chmod +x ./yt-dlp

      #- name: 查询
        #run: echo '${{ secrets.VIDEO_LIST }}' > video_list.txt && mkdir ./video_folder/ && cd ./video_folder/ && ../youtube-dl -F --ffmpeg-location ../ffmpeg-git-20210127-amd64-static/ffmpeg -a ../video_list.txt

      - name: 下载 YouTube 视频
        #run: echo '${{ secrets.VIDEO_LIST }}' > video_list.txt && mkdir ./video_folder/ && cd ./video_folder/ && ../youtube-dl -f 'best' --ffmpeg-location ../ffmpeg -a ../video_list.txt
        #run: mkdir ./video_folder/ && cd ./video_folder/ && ../youtube-dl -f 'best' --ffmpeg-location ../ffmpeg 'https://www.xvideos.com/video48321529/avengers_-_captain_marvel_get_an_amazing_dick'
        run: echo '${{ secrets.VIDEO_LIST }}' > video_list.txt && mkdir ./video_folder/ && cd ./video_folder/ && ../yt-dlp -f best,worst --ffmpeg-location ../ffmpeg-git-20210405-amd64-static/ffmpeg -a ../video_list.txt
        

      - name: 使用 rclone 将文件上传到 OneDrive
        run: rclone-v1.59.2-linux-amd64/rclone copy --config rclone.conf ./video_folder/ 'OneDrive_ty_30GB:'

